Add basic demo of DE to README
rose-pine/gtk pull request #19
Opened 2022-07-16 15:33 UTC by maybork

Resolving #17

2022-07-16 23:07 UTC, mvllow requested changes
Thank you for adding these! Just a few nitpicks on formatting 😌

![](https://pics.me.me/but-wait-theres-more-quickmeme-com-28716054.png)

2022-07-16 23:07 UTC, mvllow commented on readme.md
> +[But wait, there's more!](gallery.md)
```suggestion
## Gallery

**Rosé Pine**

![Rosé Pine settings, files, and calculator apps](https://user-images.githubusercontent.com/82605611/179361430-89f52a27-b731-44b0-bbba-9fb35567f051.png)

**Rosé Pine Moon**

![Rosé Pine Moon settings, files, and calculator apps](https://user-images.githubusercontent.com/82605611/179361439-d4ec62dd-aa1b-41dd-8f03-6102db1476f7.png)

**Rosé Pine Dawn**

![Rosé Pine Dawn settings, files, and calculator apps](https://user-images.githubusercontent.com/82605611/179361441-7b00c9fe-b43c-4ae2-8043-2751d3d5ad71.png)

[But wait, there's more!](gallery.md)
```

2022-07-16 23:09 UTC, maybork commented
Way better, thanks!

2022-07-17 03:05 UTC, mvllow approved these changes

2022-07-17 03:05 UTC, merged